const USERTYPES = {
  CUSTOMER: "CUSTOMER",
  ADMIN: "ADMIN",
  ENGINEER: "ENGINEER",
};

const USER_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
};

const TICKET_STATUS = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  BLOCKED: "BLOCKED",
  IN_PROGRESS: "IN PROGRESS",
};

module.exports = {
  USERTYPES,
  USER_STATUS,
  TICKET_STATUS,
};
